version: '3.9'

services:
  test:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: ${PROJECT_NAME}-test
    command: bash -c "while true; do sleep 10000; done"
    networks:
      - internal
      - app 
    volumes:
      - "./:/app"
    labels:
      - "traefik.enable=false"  
networks:
    app:
        external: true
        name: app
    internal:
        name: ${PROJECT_NAME}
          
   
