trigger:
  branches:
    include:
      - feature/publishHtml

parameters:
  - name: java_version
    displayName: Java Version
    type: string
    default: 8

variables:
  - name: agent
    value: devops_pool
  - group: 'SERENITYBDD'
  - name: password
    value: $(PASS)
  - name: username
    value: $(USER)

resources:
  containers:
    # based on https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#resources-containers
    - container: devops
      image: public.ecr.aws/ctsebs/devops-tools:1.14.0

    - container: build
      ${{ if contains('8,11,17',parameters.java_version) }}:
        image: public.ecr.aws/ctsebs/jdk${{parameters.java_version}}-mv36:latest


    - container: chrome_headless
      image: andres192715/java-chrome:0.0.9

stages:
  - stage: stage_prepare_automation_testing
    pool: ${{ variables.agent }}
    displayName: Prepare automation testing
    jobs:
      - job: job_running_testing
        displayName: Running testing
        container: chrome_headless
        steps:
         - checkout: self
           fetchDepth: 5
         - task: Cache@2
           condition: succeeded()
           inputs:
              key: '"gradlew" | "$(Agent.OS)" | $(Build.SourcesDirectory)/Gaia/build.gradle'
              path: $(Agent.TempDirectory)/.gradle
           displayName: Gradle Cache
         - script: |
             chmod +rwx ./Gaia
             cd Gaia
             chmod +x ./gradlew
             ./gradlew clean test -Dusername=${{ variables.username }}  -Dpassword=${{ variables.password }}  aggregate  -info
           displayName: 'Run Project'

         - task: CopyFiles@2
           condition: succeededOrFailed()
           inputs:
             sourceFolder: '$(Build.SourcesDirectory)/Gaia/target/site/serenity'
             contents: '**/*'
             targetFolder: '$(Build.ArtifactStagingDirectory)/SerenityReports'


         - task: LakshayKaushik.PublishHTMLReports.publishhtmlreport.publishhtmlreport@1
           condition: succeededOrFailed()
           displayName: 'Publish HTML Report'
           inputs:
             htmlType: 'genericHTML'
             htmlPath: '$(Build.ArtifactStagingDirectory)/SerenityReports/index.html'

         - task: PublishBuildArtifacts@1
           condition: succeededOrFailed()
           inputs:
             pathToPublish: '$(Build.ArtifactStagingDirectory)/SerenityReports'
             artifactName: 'SerenityReports'
             publishLocation: 'Container'

         - task: PublishTestResults@2
           condition: succeededOrFailed()
           inputs:
             testRunner: JUnit
             testResultsFiles: '$(Build.SourcesDirectory)/Gaia/build/test-results/test/*.xml'
             searchFolder: '$(Build.SourcesDirectory)/Gaia'
             testRunTitle: 'Serenity BDD Test Run'
             mergeTestResults: true
             publishRunAttachments: true